#include <klic/atomstuffs.h>
#define atom_call 0L+ATOMNUMBERBASE
#define atom_element 1L+ATOMNUMBERBASE
#define atom_size 2L+ATOMNUMBERBASE
#define atom_set__element 3L+ATOMNUMBERBASE
#define atom_split 4L+ATOMNUMBERBASE
#define atom_join 5L+ATOMNUMBERBASE
#define atom_vector 6L+ATOMNUMBERBASE
#define atom_string 7L+ATOMNUMBERBASE
#define atom_element__size 8L+ATOMNUMBERBASE
#define atom_search__character 9L+ATOMNUMBERBASE
#define atom_less__than 10L+ATOMNUMBERBASE
#define atom_not__less__than 11L+ATOMNUMBERBASE
#define atom_estring 12L+ATOMNUMBERBASE
#define atom_print 13L+ATOMNUMBERBASE
#define atom_int 14L+ATOMNUMBERBASE
#define atom_sin 15L+ATOMNUMBERBASE
#define atom_cos 16L+ATOMNUMBERBASE
#define atom_tan 17L+ATOMNUMBERBASE
#define atom_asin 18L+ATOMNUMBERBASE
#define atom_acos 19L+ATOMNUMBERBASE
#define atom_atan 20L+ATOMNUMBERBASE
#define atom_sinh 21L+ATOMNUMBERBASE
#define atom_cosh 22L+ATOMNUMBERBASE
#define atom_tanh 23L+ATOMNUMBERBASE
#define atom_asinh 24L+ATOMNUMBERBASE
#define atom_acosh 25L+ATOMNUMBERBASE
#define atom_atanh 26L+ATOMNUMBERBASE
#define atom_exp 27L+ATOMNUMBERBASE
#define atom_log 28L+ATOMNUMBERBASE
#define atom_sqrt 29L+ATOMNUMBERBASE
#define atom_ceil 30L+ATOMNUMBERBASE
#define atom_floor 31L+ATOMNUMBERBASE
#define atom_round 32L+ATOMNUMBERBASE
#define atom_plus 33L+ATOMNUMBERBASE
#define atom_minus 34L+ATOMNUMBERBASE
#define atom_add 35L+ATOMNUMBERBASE
#define atom_subtract 36L+ATOMNUMBERBASE
#define atom_multiply 37L+ATOMNUMBERBASE
#define atom_divide 38L+ATOMNUMBERBASE
#define atom_pow 39L+ATOMNUMBERBASE
#define atom_not__greater__than 40L+ATOMNUMBERBASE
#define atom_greater__than 41L+ATOMNUMBERBASE
#define atom_equal 42L+ATOMNUMBERBASE
#define atom_not__equal 43L+ATOMNUMBERBASE
#define atom_float 44L+ATOMNUMBERBASE
#define atom_module 45L+ATOMNUMBERBASE
#define atom_name 46L+ATOMNUMBERBASE
#define atom_arity 47L+ATOMNUMBERBASE
#define atom_apply 48L+ATOMNUMBERBASE
#define atom_predicate 49L+ATOMNUMBERBASE
#define atom_defined 50L+ATOMNUMBERBASE
#define atom_reduce 51L+ATOMNUMBERBASE
#define atom_step 52L+ATOMNUMBERBASE
#define atom_arg 53L+ATOMNUMBERBASE
#define atom_setarg 54L+ATOMNUMBERBASE
#define atom_id 55L+ATOMNUMBERBASE
#define atom_set__predicate 56L+ATOMNUMBERBASE
#define atom_normal 57L+ATOMNUMBERBASE
#define atom_get__atom 58L+ATOMNUMBERBASE
#define atom_get__atom__name 59L+ATOMNUMBERBASE
#define atom_intern 60L+ATOMNUMBERBASE
#define atom_power 61L+ATOMNUMBERBASE
#define atom_eof 62L+ATOMNUMBERBASE
#define atom_end__of__file 63L+ATOMNUMBERBASE
#define atom__5B 64L+ATOMNUMBERBASE
#define atom__7B 65L+ATOMNUMBERBASE
#define atom__20_28 66L+ATOMNUMBERBASE
#define atom__28 67L+ATOMNUMBERBASE
#define atom__2D 68L+ATOMNUMBERBASE
#define atom__5D 69L+ATOMNUMBERBASE
#define atom_never 70L+ATOMNUMBERBASE
#define atom__7D 71L+ATOMNUMBERBASE
#define atom__29 72L+ATOMNUMBERBASE
#define atom__7C 73L+ATOMNUMBERBASE
#define atom__2C 74L+ATOMNUMBERBASE
#define atom_fx 75L+ATOMNUMBERBASE
#define atom_fy 76L+ATOMNUMBERBASE
#define atom_xfx 77L+ATOMNUMBERBASE
#define atom_xfy 78L+ATOMNUMBERBASE
#define atom_yfx 79L+ATOMNUMBERBASE
#define atom_xf 80L+ATOMNUMBERBASE
#define atom_yf 81L+ATOMNUMBERBASE
#define atom_none 82L+ATOMNUMBERBASE
#define atom_yes 83L+ATOMNUMBERBASE
#define atom_no 84L+ATOMNUMBERBASE
#define atom_abnormal 85L+ATOMNUMBERBASE
#define atom_variable 86L+ATOMNUMBERBASE
#define atom_error 87L+ATOMNUMBERBASE
#define atom_number 88L+ATOMNUMBERBASE
#define atom_integer 89L+ATOMNUMBERBASE
#define atom_floating__point 90L+ATOMNUMBERBASE
#define atom_prefix 91L+ATOMNUMBERBASE
#define atom_infix 92L+ATOMNUMBERBASE
#define atom_ops 93L+ATOMNUMBERBASE
#define atom_postfix 94L+ATOMNUMBERBASE
#define atom_op 95L+ATOMNUMBERBASE
#define atom_atom 96L+ATOMNUMBERBASE
#define atom_list 97L+ATOMNUMBERBASE
#define atom_functor 98L+ATOMNUMBERBASE
#define atom__21 99L+ATOMNUMBERBASE
#define atom__3B 100L+ATOMNUMBERBASE
#define atom_void 101L+ATOMNUMBERBASE
#define atom_escaped__newline 102L+ATOMNUMBERBASE
#define atom_hexadecimal 103L+ATOMNUMBERBASE
#define atom_getc 104L+ATOMNUMBERBASE
#define atom_vtab 105L+ATOMNUMBERBASE
#define atom__3D 106L+ATOMNUMBERBASE
#define atom_var 107L+ATOMNUMBERBASE
#define atom_octal 108L+ATOMNUMBERBASE
#define atom_ungetc 109L+ATOMNUMBERBASE
#define atom_stderr 110L+ATOMNUMBERBASE
#define atom_linecount 111L+ATOMNUMBERBASE
#define atom_putc 112L+ATOMNUMBERBASE
#define atom_fwrite 113L+ATOMNUMBERBASE
#define atom_fflush 114L+ATOMNUMBERBASE
#define atom_s 115L+ATOMNUMBERBASE
#define atom_open 116L+ATOMNUMBERBASE
#define atom_unknown 117L+ATOMNUMBERBASE
#define atom_nl 118L+ATOMNUMBERBASE
#define atom__26 119L+ATOMNUMBERBASE
#define atom__3F_2D 120L+ATOMNUMBERBASE
#define atom_implicit 121L+ATOMNUMBERBASE
#define atom_local__implicit 122L+ATOMNUMBERBASE
#define atom_mode 123L+ATOMNUMBERBASE
#define atom_nospy 124L+ATOMNUMBERBASE
#define atom_public 125L+ATOMNUMBERBASE
#define atom_spy 126L+ATOMNUMBERBASE
#define atom_with__macro 127L+ATOMNUMBERBASE
#define atom__7E 128L+ATOMNUMBERBASE
#define atom__24_7E 129L+ATOMNUMBERBASE
#define atom__5C_2B 130L+ATOMNUMBERBASE
#define atom__23 131L+ATOMNUMBERBASE
#define atom__24_24_3A_3D 132L+ATOMNUMBERBASE
#define atom__24_24_3C 133L+ATOMNUMBERBASE
#define atom__24_24_3C_3D 134L+ATOMNUMBERBASE
#define atom__24_24_3D_3A_3D 135L+ATOMNUMBERBASE
#define atom__24_24_3D_3C 136L+ATOMNUMBERBASE
#define atom__24_24_3D_5C_3D 137L+ATOMNUMBERBASE
#define atom__24_24_3E 138L+ATOMNUMBERBASE
#define atom__24_24_3E_3D 139L+ATOMNUMBERBASE
#define atom__24_3A_3D 140L+ATOMNUMBERBASE
#define atom__24_3C 141L+ATOMNUMBERBASE
#define atom__24_3C_3D 142L+ATOMNUMBERBASE
#define atom__24_3D_3A_3D 143L+ATOMNUMBERBASE
#define atom__24_3D_3C 144L+ATOMNUMBERBASE
#define atom__24_3D_5C_3D 145L+ATOMNUMBERBASE
#define atom__24_3E 146L+ATOMNUMBERBASE
#define atom__24_3E_3D 147L+ATOMNUMBERBASE
#define atom__26_3C 148L+ATOMNUMBERBASE
#define atom__26_3C_3D 149L+ATOMNUMBERBASE
#define atom__26_3D_3C 150L+ATOMNUMBERBASE
#define atom__26_3E 151L+ATOMNUMBERBASE
#define atom__26_3E_3D 152L+ATOMNUMBERBASE
#define atom__24_2B_3D 153L+ATOMNUMBERBASE
#define atom__24_2D_3D 154L+ATOMNUMBERBASE
#define atom__24_2A_3D 155L+ATOMNUMBERBASE
#define atom__24_2F_3D 156L+ATOMNUMBERBASE
#define atom__2A 157L+ATOMNUMBERBASE
#define atom__2A_2A 158L+ATOMNUMBERBASE
#define atom__2B 159L+ATOMNUMBERBASE
#define atom__2D_2D_3E 160L+ATOMNUMBERBASE
#define atom__2D_3E 161L+ATOMNUMBERBASE
#define atom__2F 162L+ATOMNUMBERBASE
#define atom__2F_2F 163L+ATOMNUMBERBASE
#define atom__2F_5C 164L+ATOMNUMBERBASE
#define atom__3A 165L+ATOMNUMBERBASE
#define atom__3A_2D 166L+ATOMNUMBERBASE
#define atom__3A_3A 167L+ATOMNUMBERBASE
#define atom__3A_3D 168L+ATOMNUMBERBASE
#define atom__3C 169L+ATOMNUMBERBASE
#define atom__3C_3C 170L+ATOMNUMBERBASE
#define atom__3C_3C_3D 171L+ATOMNUMBERBASE
#define atom__3C_3D 172L+ATOMNUMBERBASE
#define atom__3C_3D_3D 173L+ATOMNUMBERBASE
#define atom__3D_2E_2E 174L+ATOMNUMBERBASE
#define atom__3D_3A_3D 175L+ATOMNUMBERBASE
#define atom__3D_3C 176L+ATOMNUMBERBASE
#define atom__3D_3D 177L+ATOMNUMBERBASE
#define atom__3D_3E 178L+ATOMNUMBERBASE
#define atom__3D_5C_3D 179L+ATOMNUMBERBASE
#define atom__3E 180L+ATOMNUMBERBASE
#define atom__3E_3D 181L+ATOMNUMBERBASE
#define atom__2B_3D 182L+ATOMNUMBERBASE
#define atom__2D_3D 183L+ATOMNUMBERBASE
#define atom__2A_3D 184L+ATOMNUMBERBASE
#define atom__2F_3D 185L+ATOMNUMBERBASE
#define atom__3E_3E 186L+ATOMNUMBERBASE
#define atom__40 187L+ATOMNUMBERBASE
#define atom__40_3C 188L+ATOMNUMBERBASE
#define atom__40_3D_3C 189L+ATOMNUMBERBASE
#define atom__40_3E 190L+ATOMNUMBERBASE
#define atom__40_3E_3D 191L+ATOMNUMBERBASE
#define atom__5C_2F 192L+ATOMNUMBERBASE
#define atom__5C_3D 193L+ATOMNUMBERBASE
#define atom__5C_3D_3D 194L+ATOMNUMBERBASE
#define atom__5E 195L+ATOMNUMBERBASE
#define atom_is 196L+ATOMNUMBERBASE
#define atom_mod 197L+ATOMNUMBERBASE
#define atom_xor 198L+ATOMNUMBERBASE
#define atom__2B_2B 199L+ATOMNUMBERBASE
#define atom__2D_2D 200L+ATOMNUMBERBASE
#define atom_stdin 201L+ATOMNUMBERBASE
#define atom_stdout 202L+ATOMNUMBERBASE
#define atom_read__open 203L+ATOMNUMBERBASE
#define atom_write__open 204L+ATOMNUMBERBASE
#define atom_append__open 205L+ATOMNUMBERBASE
#define atom_update__open 206L+ATOMNUMBERBASE
#define atom_unix 207L+ATOMNUMBERBASE
#define atom_string__output 208L+ATOMNUMBERBASE
#define atom_string__input 209L+ATOMNUMBERBASE
#define atom_gett 210L+ATOMNUMBERBASE
#define atom_getwt 211L+ATOMNUMBERBASE
#define atom_putt 212L+ATOMNUMBERBASE
#define atom_puttq 213L+ATOMNUMBERBASE
#define atom_putwt 214L+ATOMNUMBERBASE
#define atom_putwtq 215L+ATOMNUMBERBASE
#define atom_addop 216L+ATOMNUMBERBASE
#define atom_rmop 217L+ATOMNUMBERBASE
#define atom_on__error 218L+ATOMNUMBERBASE
#define atom_connect 219L+ATOMNUMBERBASE
#define atom_bind 220L+ATOMNUMBERBASE
#define atom_accept 221L+ATOMNUMBERBASE
#define atom_connect2 222L+ATOMNUMBERBASE
#define atom_accept2 223L+ATOMNUMBERBASE
#define atom_sym 224L+ATOMNUMBERBASE
#define atom_unparser 225L+ATOMNUMBERBASE
#define atom_unparse 226L+ATOMNUMBERBASE
#define atom_unwparse 227L+ATOMNUMBERBASE
#define atom_qtd 228L+ATOMNUMBERBASE
#define atom_alf 229L+ATOMNUMBERBASE
#define atom_do 230L+ATOMNUMBERBASE
#define atom_empty 231L+ATOMNUMBERBASE
#define atom_put 232L+ATOMNUMBERBASE
#define atom_get 233L+ATOMNUMBERBASE
#define atom_get__if__any 234L+ATOMNUMBERBASE
#define atom_get__all 235L+ATOMNUMBERBASE
#define atom_carbon__copy 236L+ATOMNUMBERBASE
#define atom_get__max__if__any 237L+ATOMNUMBERBASE
#define atom_get__min__if__any 238L+ATOMNUMBERBASE
#define atom_get__if__any__and__put 239L+ATOMNUMBERBASE
#define atom_get__and__put__if__any 240L+ATOMNUMBERBASE
#define atom_get__and__put 241L+ATOMNUMBERBASE
#define atom_comparator 242L+ATOMNUMBERBASE
#define atom_sort 243L+ATOMNUMBERBASE
#define atom_pool 244L+ATOMNUMBERBASE
#define atom_n 245L+ATOMNUMBERBASE
#define atom_time 246L+ATOMNUMBERBASE
#define atom_signal__stream 247L+ATOMNUMBERBASE
#define atom_pipe 248L+ATOMNUMBERBASE
#define atom_system 249L+ATOMNUMBERBASE
#define atom_cd 250L+ATOMNUMBERBASE
#define atom_unlink 251L+ATOMNUMBERBASE
#define atom_mktemp 252L+ATOMNUMBERBASE
#define atom_access 253L+ATOMNUMBERBASE
#define atom_chmod 254L+ATOMNUMBERBASE
#define atom_umask 255L+ATOMNUMBERBASE
#define atom_getenv 256L+ATOMNUMBERBASE
#define atom_putenv 257L+ATOMNUMBERBASE
#define atom_kill 258L+ATOMNUMBERBASE
#define atom_fork 259L+ATOMNUMBERBASE
#define atom_fork__with__pipes 260L+ATOMNUMBERBASE
#define atom_inet 261L+ATOMNUMBERBASE
#define atom_fread 262L+ATOMNUMBERBASE
#define atom_feof 263L+ATOMNUMBERBASE
#define atom_sync 264L+ATOMNUMBERBASE
#define atom_parent 265L+ATOMNUMBERBASE
#define atom_child 266L+ATOMNUMBERBASE
#define atom_fseek 267L+ATOMNUMBERBASE
#define atom_ftell 268L+ATOMNUMBERBASE
#define atom_fclose 269L+ATOMNUMBERBASE
#define atom_stdio 270L+ATOMNUMBERBASE
#define atom_flush 271L+ATOMNUMBERBASE
#define atom_puts 272L+ATOMNUMBERBASE
#define atom_builtin 273L+ATOMNUMBERBASE
#define atom_integer__arithmetics 274L+ATOMNUMBERBASE
#define atom_floating__arithmetics 275L+ATOMNUMBERBASE
#define atom_bblt__add 276L+ATOMNUMBERBASE
#define atom_bblt__sub 277L+ATOMNUMBERBASE
#define atom_bblt__mult 278L+ATOMNUMBERBASE
#define atom_bblt__div 279L+ATOMNUMBERBASE
#define atom_modulo 280L+ATOMNUMBERBASE
#define atom_bblt__mod 281L+ATOMNUMBERBASE
#define atom_and 282L+ATOMNUMBERBASE
#define atom_bblt__and 283L+ATOMNUMBERBASE
#define atom_or 284L+ATOMNUMBERBASE
#define atom_bblt__or 285L+ATOMNUMBERBASE
#define atom_exclusive__or 286L+ATOMNUMBERBASE
#define atom_bblt__exclusive__or 287L+ATOMNUMBERBASE
#define atom_shift__left 288L+ATOMNUMBERBASE
#define atom_bblt__lshift 289L+ATOMNUMBERBASE
#define atom_shift__right 290L+ATOMNUMBERBASE
#define atom_bblt__rshift 291L+ATOMNUMBERBASE
#define atom_complement 292L+ATOMNUMBERBASE
#define atom_bblt__complement 293L+ATOMNUMBERBASE
#define atom_bblt__plus 294L+ATOMNUMBERBASE
#define atom_bblt__minus 295L+ATOMNUMBERBASE
#define atom_floating__point__add 296L+ATOMNUMBERBASE
#define atom_bblt__float__add 297L+ATOMNUMBERBASE
#define atom_floating__point__subtract 298L+ATOMNUMBERBASE
#define atom_bblt__float__sub 299L+ATOMNUMBERBASE
#define atom_floating__point__multiply 300L+ATOMNUMBERBASE
#define atom_bblt__float__mult 301L+ATOMNUMBERBASE
#define atom_floating__point__divide 302L+ATOMNUMBERBASE
#define atom_bblt__float__div 303L+ATOMNUMBERBASE
#define atom_floating__point__power 304L+ATOMNUMBERBASE
#define atom_bblt__float__pow 305L+ATOMNUMBERBASE
#define atom_floating__point__sin 306L+ATOMNUMBERBASE
#define atom_bblt__float__sin 307L+ATOMNUMBERBASE
#define atom_floating__point__cos 308L+ATOMNUMBERBASE
#define atom_bblt__float__cos 309L+ATOMNUMBERBASE
#define atom_floating__point__tan 310L+ATOMNUMBERBASE
#define atom_bblt__float__tan 311L+ATOMNUMBERBASE
#define atom_floating__point__asin 312L+ATOMNUMBERBASE
#define atom_bblt__float__asin 313L+ATOMNUMBERBASE
#define atom_floating__point__acos 314L+ATOMNUMBERBASE
#define atom_bblt__float__acos 315L+ATOMNUMBERBASE
#define atom_floating__point__atan 316L+ATOMNUMBERBASE
#define atom_bblt__float__atan 317L+ATOMNUMBERBASE
#define atom_floating__point__sinh 318L+ATOMNUMBERBASE
#define atom_bblt__float__sinh 319L+ATOMNUMBERBASE
#define atom_floating__point__cosh 320L+ATOMNUMBERBASE
#define atom_bblt__float__cosh 321L+ATOMNUMBERBASE
#define atom_floating__point__tanh 322L+ATOMNUMBERBASE
#define atom_bblt__float__tanh 323L+ATOMNUMBERBASE
#define atom_floating__point__exp 324L+ATOMNUMBERBASE
#define atom_bblt__float__exp 325L+ATOMNUMBERBASE
#define atom_floating__point__log 326L+ATOMNUMBERBASE
#define atom_bblt__float__log 327L+ATOMNUMBERBASE
#define atom_floating__point__sqrt 328L+ATOMNUMBERBASE
#define atom_bblt__float__sqrt 329L+ATOMNUMBERBASE
#define atom_floating__point__ceil 330L+ATOMNUMBERBASE
#define atom_bblt__float__ceil 331L+ATOMNUMBERBASE
#define atom_floating__point__floor 332L+ATOMNUMBERBASE
#define atom_bblt__float__floor 333L+ATOMNUMBERBASE
#define atom_floating__point__to__integer 334L+ATOMNUMBERBASE
#define atom_bblt__fix 335L+ATOMNUMBERBASE
#define atom_current__node 336L+ATOMNUMBERBASE
#define atom_bblt__current__node 337L+ATOMNUMBERBASE
#define atom_object 338L+ATOMNUMBERBASE
#define atom_gblt__hash 339L+ATOMNUMBERBASE
#define atom_gblt__deep__hash 340L+ATOMNUMBERBASE
#define atom_gblt__compare 341L+ATOMNUMBERBASE
#define atom_gblt__current__prio 342L+ATOMNUMBERBASE
#define atom_gblt__wait 343L+ATOMNUMBERBASE
#define atom_gblt__list 344L+ATOMNUMBERBASE
#define atom_gblt__atom 345L+ATOMNUMBERBASE
#define atom_gblt__integer 346L+ATOMNUMBERBASE
#define atom_atomic 347L+ATOMNUMBERBASE
#define atom_gblt__atomic 348L+ATOMNUMBERBASE
#define atom_gblt__float 349L+ATOMNUMBERBASE
#define atom_gblt__size__of__vector 350L+ATOMNUMBERBASE
#define atom_gblt__element__of__vector 351L+ATOMNUMBERBASE
#define atom_gblt__size__of__string 352L+ATOMNUMBERBASE
#define atom_gblt__element__size__of__string 353L+ATOMNUMBERBASE
#define atom_gblt__is__string 354L+ATOMNUMBERBASE
#define atom_gblt__element__of__string 355L+ATOMNUMBERBASE
#define atom_gblt__pfunctor 356L+ATOMNUMBERBASE
#define atom_gblt__arity 357L+ATOMNUMBERBASE
#define atom_any 358L+ATOMNUMBERBASE
#define atom_gblt__arg 359L+ATOMNUMBERBASE
#define atom_gblt__less 360L+ATOMNUMBERBASE
#define atom_gblt__greater__or__eq 361L+ATOMNUMBERBASE
#define atom_gblt__greater 362L+ATOMNUMBERBASE
#define atom_gblt__less__or__eq 363L+ATOMNUMBERBASE
#define atom_gblt__eq 364L+ATOMNUMBERBASE
#define atom_gblt__not__eq 365L+ATOMNUMBERBASE
#define atom_gblt__diff 366L+ATOMNUMBERBASE
#define atom_gblt__and 367L+ATOMNUMBERBASE
#define atom_gblt__or 368L+ATOMNUMBERBASE
#define atom_gblt__exclusive__or 369L+ATOMNUMBERBASE
#define atom_gblt__rshift 370L+ATOMNUMBERBASE
#define atom_gblt__lshift 371L+ATOMNUMBERBASE
#define atom_gblt__add 372L+ATOMNUMBERBASE
#define atom_gblt__subtract 373L+ATOMNUMBERBASE
#define atom_gblt__multiply 374L+ATOMNUMBERBASE
#define atom_gblt__divide 375L+ATOMNUMBERBASE
#define atom_gblt__modulo 376L+ATOMNUMBERBASE
#define atom_gblt__complement 377L+ATOMNUMBERBASE
#define atom_gblt__plus 378L+ATOMNUMBERBASE
#define atom_gblt__minus 379L+ATOMNUMBERBASE
#define atom_gblt__fix 380L+ATOMNUMBERBASE
#define atom_gblt__tag 381L+ATOMNUMBERBASE
#define atom_gblt__value 382L+ATOMNUMBERBASE
#define atom_bound 383L+ATOMNUMBERBASE
#define atom_gblt__display__console 384L+ATOMNUMBERBASE
#define atom_hash 385L+ATOMNUMBERBASE
#define atom_compare 386L+ATOMNUMBERBASE
#define atom_current__priority 387L+ATOMNUMBERBASE
#define atom_wait 388L+ATOMNUMBERBASE
#define atom_vector__element 389L+ATOMNUMBERBASE
#define atom_string__element 390L+ATOMNUMBERBASE
#define atom_diff 391L+ATOMNUMBERBASE
#define atom_tag__and__value 392L+ATOMNUMBERBASE
#define atom_display__console 393L+ATOMNUMBERBASE
#define atom_put__console 394L+ATOMNUMBERBASE
#define atom__24 395L+ATOMNUMBERBASE
#define atom_interrupt 396L+ATOMNUMBERBASE
#define atom_e 397L+ATOMNUMBERBASE
#define atom_otherwise 398L+ATOMNUMBERBASE
#define atom_alternatively 399L+ATOMNUMBERBASE
#define atom_head 400L+ATOMNUMBERBASE
#define atom_cdr 401L+ATOMNUMBERBASE
#define atom_car 402L+ATOMNUMBERBASE
#define atom_inline 403L+ATOMNUMBERBASE
#define atom_new 404L+ATOMNUMBERBASE
#define atom_generic 405L+ATOMNUMBERBASE
#define atom_lower__priority 406L+ATOMNUMBERBASE
#define atom_lab 407L+ATOMNUMBERBASE
#define atom_a 408L+ATOMNUMBERBASE
#define atom_clause 409L+ATOMNUMBERBASE
#define atom_il 410L+ATOMNUMBERBASE
#define atom_gg 411L+ATOMNUMBERBASE
#define atom_gp 412L+ATOMNUMBERBASE
#define atom_gb 413L+ATOMNUMBERBASE
#define atom__24macroexpanded 414L+ATOMNUMBERBASE
#define atom_gcall 415L+ATOMNUMBERBASE
#define atom_xcall 416L+ATOMNUMBERBASE
#define atom_priority 417L+ATOMNUMBERBASE
#define atom_node 418L+ATOMNUMBERBASE
#define atom_xpcall 419L+ATOMNUMBERBASE
#define atom_pcall 420L+ATOMNUMBERBASE
#define atom_xlcall 421L+ATOMNUMBERBASE
#define atom_lcall 422L+ATOMNUMBERBASE
#define atom_xthrow 423L+ATOMNUMBERBASE
#define atom_throw 424L+ATOMNUMBERBASE
#define atom_rename 425L+ATOMNUMBERBASE
#define atom_mkfunct 426L+ATOMNUMBERBASE
#define atom_mkvect 427L+ATOMNUMBERBASE
#define atom_cons 428L+ATOMNUMBERBASE
#define atom_version_203_2E01 429L+ATOMNUMBERBASE
#define atom_Sun_2C_2010_20Apr_202016_2019_3A09_3A11_20_2B0900 430L+ATOMNUMBERBASE
#define atom_end__sw 431L+ATOMNUMBERBASE
#define atom_funct 432L+ATOMNUMBERBASE
#define atom_abs 433L+ATOMNUMBERBASE
#define atom_rel 434L+ATOMNUMBERBASE
#define atom_qp 435L+ATOMNUMBERBASE
#define atom_known 436L+ATOMNUMBERBASE
#define atom_other 437L+ATOMNUMBERBASE
#define atom_alter 438L+ATOMNUMBERBASE
#define atom_l 439L+ATOMNUMBERBASE
#define atom_x 440L+ATOMNUMBERBASE
#define atom_if__ref 441L+ATOMNUMBERBASE
#define atom_if__not__ref 442L+ATOMNUMBERBASE
#define atom_v 443L+ATOMNUMBERBASE
#define atom_deref 444L+ATOMNUMBERBASE
#define atom_sw__tag 445L+ATOMNUMBERBASE
#define atom_case__label 446L+ATOMNUMBERBASE
#define atom_if__not__int 447L+ATOMNUMBERBASE
#define atom_if__int 448L+ATOMNUMBERBASE
#define atom_f 449L+ATOMNUMBERBASE
#define atom_o 450L+ATOMNUMBERBASE
#define atom_if__not__gobj 451L+ATOMNUMBERBASE
#define atom_if__not__class 452L+ATOMNUMBERBASE
#define atom_goto 453L+ATOMNUMBERBASE
#define atom_if__not 454L+ATOMNUMBERBASE
#define atom_if__funct__not 455L+ATOMNUMBERBASE
#define atom_sw__sym 456L+ATOMNUMBERBASE
#define atom_sw__int 457L+ATOMNUMBERBASE
#define atom_sw__funct 458L+ATOMNUMBERBASE
#define atom_case__sym 459L+ATOMNUMBERBASE
#define atom_case__int 460L+ATOMNUMBERBASE
#define atom_case__funct 461L+ATOMNUMBERBASE
#define atom_label 462L+ATOMNUMBERBASE
#define atom_gblt__pred 463L+ATOMNUMBERBASE
#define atom_guard__generic 464L+ATOMNUMBERBASE
#define atom_eq 465L+ATOMNUMBERBASE
#define atom_if__not__eq 466L+ATOMNUMBERBASE
#define atom_load__generic__arg 467L+ATOMNUMBERBASE
#define atom_make__cons 468L+ATOMNUMBERBASE
#define atom_make__functor 469L+ATOMNUMBERBASE
#define atom_alloc__functor__id 470L+ATOMNUMBERBASE
#define atom_make__vector 471L+ATOMNUMBERBASE
#define atom_const 472L+ATOMNUMBERBASE
#define atom_alloc__value 473L+ATOMNUMBERBASE
#define atom_alloc__const 474L+ATOMNUMBERBASE
#define atom_exec 475L+ATOMNUMBERBASE
#define atom_execute 476L+ATOMNUMBERBASE
#define atom_proceed 477L+ATOMNUMBERBASE
#define atom_bblt 478L+ATOMNUMBERBASE
#define atom_push__goal 479L+ATOMNUMBERBASE
#define atom_gnew 480L+ATOMNUMBERBASE
#define atom_new__generic 481L+ATOMNUMBERBASE
#define atom_call__generic 482L+ATOMNUMBERBASE
#define atom_throw__goal 483L+ATOMNUMBERBASE
#define atom_set__pred 484L+ATOMNUMBERBASE
#define atom_ext 485L+ATOMNUMBERBASE
#define atom_heappos 486L+ATOMNUMBERBASE
#define atom_set__ext__pred 487L+ATOMNUMBERBASE
#define atom_enq__at__prio__no__check 488L+ATOMNUMBERBASE
#define atom_enq__at__prio 489L+ATOMNUMBERBASE
#define atom_enq__at__lower__prio__no__check 490L+ATOMNUMBERBASE
#define atom_enq__at__lower__prio 491L+ATOMNUMBERBASE
#define atom_alloc__var 492L+ATOMNUMBERBASE
#define atom_make__space 493L+ATOMNUMBERBASE
#define atom_unify__value 494L+ATOMNUMBERBASE
#define atom_unify 495L+ATOMNUMBERBASE
#define atom_set__const 496L+ATOMNUMBERBASE
#define atom_set__value 497L+ATOMNUMBERBASE
#define atom_set__newvar 498L+ATOMNUMBERBASE
#define atom_store__generic__arg 499L+ATOMNUMBERBASE
#define atom_load__const 500L+ATOMNUMBERBASE
#define atom_get__elem 501L+ATOMNUMBERBASE
#define atom_load__newvar 502L+ATOMNUMBERBASE
#define atom_move 503L+ATOMNUMBERBASE
#define atom_r 504L+ATOMNUMBERBASE
#define atom_guse 505L+ATOMNUMBERBASE
#define atom_set__qp 506L+ATOMNUMBERBASE
#define atom_case__default 507L+ATOMNUMBERBASE
#define atom_clear__reason 508L+ATOMNUMBERBASE
#define atom_user__error 509L+ATOMNUMBERBASE
#define atom_alloc__elem 510L+ATOMNUMBERBASE
#define atom_if__list 511L+ATOMNUMBERBASE
#define atom_if__not__list 512L+ATOMNUMBERBASE
#define atom_if__funct 513L+ATOMNUMBERBASE
#define atom_if__not__funct 514L+ATOMNUMBERBASE
#define atom_set__elem 515L+ATOMNUMBERBASE
#define atom_gblt 516L+ATOMNUMBERBASE
#define atom_equiv 517L+ATOMNUMBERBASE
#define atom_info 518L+ATOMNUMBERBASE
#define atom_class 519L+ATOMNUMBERBASE
#define atom_pred 520L+ATOMNUMBERBASE
#define atom_true 521L+ATOMNUMBERBASE
#define atom_functor__table 522L+ATOMNUMBERBASE
#define atom_merge 523L+ATOMNUMBERBASE
#define atom_builtin__utility 524L+ATOMNUMBERBASE
#define atom_g 525L+ATOMNUMBERBASE
#define atom__60 526L+ATOMNUMBERBASE
#define atom__60_60 527L+ATOMNUMBERBASE
#define atom_c 528L+ATOMNUMBERBASE
#define atom_key 529L+ATOMNUMBERBASE
#define atom_lf 530L+ATOMNUMBERBASE
#define atom_cr 531L+ATOMNUMBERBASE
#define atom_b 532L+ATOMNUMBERBASE
#define atom_fix 533L+ATOMNUMBERBASE
#define atom_expanded 534L+ATOMNUMBERBASE
#define atom_unbound 535L+ATOMNUMBERBASE
#define atom_new__functor 536L+ATOMNUMBERBASE
#define atom_set__string__element 537L+ATOMNUMBERBASE
#define atom_set__vector__element 538L+ATOMNUMBERBASE
#define atom_new__string 539L+ATOMNUMBERBASE
#define atom_new__vector 540L+ATOMNUMBERBASE
#define atom_predicate__to__code 541L+ATOMNUMBERBASE
#define atom_string__less__than 542L+ATOMNUMBERBASE
#define atom_string__not__less__than 543L+ATOMNUMBERBASE
#define atom_code 544L+ATOMNUMBERBASE
#define atom_general 545L+ATOMNUMBERBASE
#define atom__5C 546L+ATOMNUMBERBASE
#define atom_byte__string 547L+ATOMNUMBERBASE
#define atom_inputfile 548L+ATOMNUMBERBASE
#define atom_fileopen 549L+ATOMNUMBERBASE
#define atom_fileoutput 550L+ATOMNUMBERBASE
#define atom_compiling__module 551L+ATOMNUMBERBASE
#define atom_compiling__predicate 552L+ATOMNUMBERBASE
#define atom_ambiguous 553L+ATOMNUMBERBASE
#define atom_token 554L+ATOMNUMBERBASE
#define atom_was 555L+ATOMNUMBERBASE
#define atom_found 556L+ATOMNUMBERBASE
#define atom_end 557L+ATOMNUMBERBASE
#define atom__24VAR 558L+ATOMNUMBERBASE
#define atom_with 559L+ATOMNUMBERBASE
