#include <klic/atomstuffs.h>
#define atom_call 0L+ATOMNUMBERBASE
#define atom_element 1L+ATOMNUMBERBASE
#define atom_size 2L+ATOMNUMBERBASE
#define atom_set__element 3L+ATOMNUMBERBASE
#define atom_split 4L+ATOMNUMBERBASE
#define atom_join 5L+ATOMNUMBERBASE
#define atom_vector 6L+ATOMNUMBERBASE
#define atom_string 7L+ATOMNUMBERBASE
#define atom_element__size 8L+ATOMNUMBERBASE
#define atom_search__character 9L+ATOMNUMBERBASE
#define atom_less__than 10L+ATOMNUMBERBASE
#define atom_not__less__than 11L+ATOMNUMBERBASE
#define atom_estring 12L+ATOMNUMBERBASE
#define atom_print 13L+ATOMNUMBERBASE
#define atom_int 14L+ATOMNUMBERBASE
#define atom_sin 15L+ATOMNUMBERBASE
#define atom_cos 16L+ATOMNUMBERBASE
#define atom_tan 17L+ATOMNUMBERBASE
#define atom_asin 18L+ATOMNUMBERBASE
#define atom_acos 19L+ATOMNUMBERBASE
#define atom_atan 20L+ATOMNUMBERBASE
#define atom_sinh 21L+ATOMNUMBERBASE
#define atom_cosh 22L+ATOMNUMBERBASE
#define atom_tanh 23L+ATOMNUMBERBASE
#define atom_asinh 24L+ATOMNUMBERBASE
#define atom_acosh 25L+ATOMNUMBERBASE
#define atom_atanh 26L+ATOMNUMBERBASE
#define atom_exp 27L+ATOMNUMBERBASE
#define atom_log 28L+ATOMNUMBERBASE
#define atom_sqrt 29L+ATOMNUMBERBASE
#define atom_ceil 30L+ATOMNUMBERBASE
#define atom_floor 31L+ATOMNUMBERBASE
#define atom_round 32L+ATOMNUMBERBASE
#define atom_plus 33L+ATOMNUMBERBASE
#define atom_minus 34L+ATOMNUMBERBASE
#define atom_add 35L+ATOMNUMBERBASE
#define atom_subtract 36L+ATOMNUMBERBASE
#define atom_multiply 37L+ATOMNUMBERBASE
#define atom_divide 38L+ATOMNUMBERBASE
#define atom_pow 39L+ATOMNUMBERBASE
#define atom_not__greater__than 40L+ATOMNUMBERBASE
#define atom_greater__than 41L+ATOMNUMBERBASE
#define atom_equal 42L+ATOMNUMBERBASE
#define atom_not__equal 43L+ATOMNUMBERBASE
#define atom_float 44L+ATOMNUMBERBASE
#define atom_module 45L+ATOMNUMBERBASE
#define atom_name 46L+ATOMNUMBERBASE
#define atom_arity 47L+ATOMNUMBERBASE
#define atom_apply 48L+ATOMNUMBERBASE
#define atom_predicate 49L+ATOMNUMBERBASE
#define atom_defined 50L+ATOMNUMBERBASE
#define atom_reduce 51L+ATOMNUMBERBASE
#define atom_step 52L+ATOMNUMBERBASE
#define atom_arg 53L+ATOMNUMBERBASE
#define atom_setarg 54L+ATOMNUMBERBASE
#define atom_id 55L+ATOMNUMBERBASE
#define atom_set__predicate 56L+ATOMNUMBERBASE
#define atom_normal 57L+ATOMNUMBERBASE
#define atom_get__atom 58L+ATOMNUMBERBASE
#define atom_get__atom__name 59L+ATOMNUMBERBASE
#define atom_intern 60L+ATOMNUMBERBASE
#define atom_power 61L+ATOMNUMBERBASE
#define atom_eof 62L+ATOMNUMBERBASE
#define atom_end__of__file 63L+ATOMNUMBERBASE
#define atom__5B 64L+ATOMNUMBERBASE
#define atom__7B 65L+ATOMNUMBERBASE
#define atom__20_28 66L+ATOMNUMBERBASE
#define atom__28 67L+ATOMNUMBERBASE
#define atom__2D 68L+ATOMNUMBERBASE
#define atom__5D 69L+ATOMNUMBERBASE
#define atom_never 70L+ATOMNUMBERBASE
#define atom__7D 71L+ATOMNUMBERBASE
#define atom__29 72L+ATOMNUMBERBASE
#define atom__7C 73L+ATOMNUMBERBASE
#define atom__2C 74L+ATOMNUMBERBASE
#define atom_fx 75L+ATOMNUMBERBASE
#define atom_fy 76L+ATOMNUMBERBASE
#define atom_xfx 77L+ATOMNUMBERBASE
#define atom_xfy 78L+ATOMNUMBERBASE
#define atom_yfx 79L+ATOMNUMBERBASE
#define atom_xf 80L+ATOMNUMBERBASE
#define atom_yf 81L+ATOMNUMBERBASE
#define atom_none 82L+ATOMNUMBERBASE
#define atom_yes 83L+ATOMNUMBERBASE
#define atom_no 84L+ATOMNUMBERBASE
#define atom_abnormal 85L+ATOMNUMBERBASE
#define atom_variable 86L+ATOMNUMBERBASE
#define atom_error 87L+ATOMNUMBERBASE
#define atom_number 88L+ATOMNUMBERBASE
#define atom_integer 89L+ATOMNUMBERBASE
#define atom_floating__point 90L+ATOMNUMBERBASE
#define atom_prefix 91L+ATOMNUMBERBASE
#define atom_infix 92L+ATOMNUMBERBASE
#define atom_ops 93L+ATOMNUMBERBASE
#define atom_postfix 94L+ATOMNUMBERBASE
#define atom_op 95L+ATOMNUMBERBASE
#define atom_atom 96L+ATOMNUMBERBASE
#define atom_list 97L+ATOMNUMBERBASE
#define atom_functor 98L+ATOMNUMBERBASE
#define atom__21 99L+ATOMNUMBERBASE
#define atom__3B 100L+ATOMNUMBERBASE
#define atom_void 101L+ATOMNUMBERBASE
#define atom_escaped__newline 102L+ATOMNUMBERBASE
#define atom_hexadecimal 103L+ATOMNUMBERBASE
#define atom_getc 104L+ATOMNUMBERBASE
#define atom_vtab 105L+ATOMNUMBERBASE
#define atom__3D 106L+ATOMNUMBERBASE
#define atom_var 107L+ATOMNUMBERBASE
#define atom_octal 108L+ATOMNUMBERBASE
#define atom_ungetc 109L+ATOMNUMBERBASE
#define atom_stderr 110L+ATOMNUMBERBASE
#define atom_linecount 111L+ATOMNUMBERBASE
#define atom_putc 112L+ATOMNUMBERBASE
#define atom_fwrite 113L+ATOMNUMBERBASE
#define atom_fflush 114L+ATOMNUMBERBASE
#define atom_s 115L+ATOMNUMBERBASE
#define atom_open 116L+ATOMNUMBERBASE
#define atom_unknown 117L+ATOMNUMBERBASE
#define atom_nl 118L+ATOMNUMBERBASE
#define atom__26 119L+ATOMNUMBERBASE
#define atom__3F_2D 120L+ATOMNUMBERBASE
#define atom_implicit 121L+ATOMNUMBERBASE
#define atom_local__implicit 122L+ATOMNUMBERBASE
#define atom_mode 123L+ATOMNUMBERBASE
#define atom_nospy 124L+ATOMNUMBERBASE
#define atom_public 125L+ATOMNUMBERBASE
#define atom_spy 126L+ATOMNUMBERBASE
#define atom_with__macro 127L+ATOMNUMBERBASE
#define atom__7E 128L+ATOMNUMBERBASE
#define atom__24_7E 129L+ATOMNUMBERBASE
#define atom__5C_2B 130L+ATOMNUMBERBASE
#define atom__23 131L+ATOMNUMBERBASE
#define atom__24_24_3A_3D 132L+ATOMNUMBERBASE
#define atom__24_24_3C 133L+ATOMNUMBERBASE
#define atom__24_24_3C_3D 134L+ATOMNUMBERBASE
#define atom__24_24_3D_3A_3D 135L+ATOMNUMBERBASE
#define atom__24_24_3D_3C 136L+ATOMNUMBERBASE
#define atom__24_24_3D_5C_3D 137L+ATOMNUMBERBASE
#define atom__24_24_3E 138L+ATOMNUMBERBASE
#define atom__24_24_3E_3D 139L+ATOMNUMBERBASE
#define atom__24_3A_3D 140L+ATOMNUMBERBASE
#define atom__24_3C 141L+ATOMNUMBERBASE
#define atom__24_3C_3D 142L+ATOMNUMBERBASE
#define atom__24_3D_3A_3D 143L+ATOMNUMBERBASE
#define atom__24_3D_3C 144L+ATOMNUMBERBASE
#define atom__24_3D_5C_3D 145L+ATOMNUMBERBASE
#define atom__24_3E 146L+ATOMNUMBERBASE
#define atom__24_3E_3D 147L+ATOMNUMBERBASE
#define atom__26_3C 148L+ATOMNUMBERBASE
#define atom__26_3C_3D 149L+ATOMNUMBERBASE
#define atom__26_3D_3C 150L+ATOMNUMBERBASE
#define atom__26_3E 151L+ATOMNUMBERBASE
#define atom__26_3E_3D 152L+ATOMNUMBERBASE
#define atom__24_2B_3D 153L+ATOMNUMBERBASE
#define atom__24_2D_3D 154L+ATOMNUMBERBASE
#define atom__24_2A_3D 155L+ATOMNUMBERBASE
#define atom__24_2F_3D 156L+ATOMNUMBERBASE
#define atom__2A 157L+ATOMNUMBERBASE
#define atom__2A_2A 158L+ATOMNUMBERBASE
#define atom__2B 159L+ATOMNUMBERBASE
#define atom__2D_2D_3E 160L+ATOMNUMBERBASE
#define atom__2D_3E 161L+ATOMNUMBERBASE
#define atom__2F 162L+ATOMNUMBERBASE
#define atom__2F_2F 163L+ATOMNUMBERBASE
#define atom__2F_5C 164L+ATOMNUMBERBASE
#define atom__3A 165L+ATOMNUMBERBASE
#define atom__3A_2D 166L+ATOMNUMBERBASE
#define atom__3A_3A 167L+ATOMNUMBERBASE
#define atom__3A_3D 168L+ATOMNUMBERBASE
#define atom__3C 169L+ATOMNUMBERBASE
#define atom__3C_3C 170L+ATOMNUMBERBASE
#define atom__3C_3C_3D 171L+ATOMNUMBERBASE
#define atom__3C_3D 172L+ATOMNUMBERBASE
#define atom__3C_3D_3D 173L+ATOMNUMBERBASE
#define atom__3D_2E_2E 174L+ATOMNUMBERBASE
#define atom__3D_3A_3D 175L+ATOMNUMBERBASE
#define atom__3D_3C 176L+ATOMNUMBERBASE
#define atom__3D_3D 177L+ATOMNUMBERBASE
#define atom__3D_3E 178L+ATOMNUMBERBASE
#define atom__3D_5C_3D 179L+ATOMNUMBERBASE
#define atom__3E 180L+ATOMNUMBERBASE
#define atom__3E_3D 181L+ATOMNUMBERBASE
#define atom__2B_3D 182L+ATOMNUMBERBASE
#define atom__2D_3D 183L+ATOMNUMBERBASE
#define atom__2A_3D 184L+ATOMNUMBERBASE
#define atom__2F_3D 185L+ATOMNUMBERBASE
#define atom__3E_3E 186L+ATOMNUMBERBASE
#define atom__40 187L+ATOMNUMBERBASE
#define atom__40_3C 188L+ATOMNUMBERBASE
#define atom__40_3D_3C 189L+ATOMNUMBERBASE
#define atom__40_3E 190L+ATOMNUMBERBASE
#define atom__40_3E_3D 191L+ATOMNUMBERBASE
#define atom__5C_2F 192L+ATOMNUMBERBASE
#define atom__5C_3D 193L+ATOMNUMBERBASE
#define atom__5C_3D_3D 194L+ATOMNUMBERBASE
#define atom__5E 195L+ATOMNUMBERBASE
#define atom_is 196L+ATOMNUMBERBASE
#define atom_mod 197L+ATOMNUMBERBASE
#define atom_xor 198L+ATOMNUMBERBASE
#define atom__2B_2B 199L+ATOMNUMBERBASE
#define atom__2D_2D 200L+ATOMNUMBERBASE
#define atom_stdin 201L+ATOMNUMBERBASE
#define atom_stdout 202L+ATOMNUMBERBASE
#define atom_read__open 203L+ATOMNUMBERBASE
#define atom_write__open 204L+ATOMNUMBERBASE
#define atom_append__open 205L+ATOMNUMBERBASE
#define atom_update__open 206L+ATOMNUMBERBASE
#define atom_unix 207L+ATOMNUMBERBASE
#define atom_string__output 208L+ATOMNUMBERBASE
#define atom_string__input 209L+ATOMNUMBERBASE
#define atom_gett 210L+ATOMNUMBERBASE
#define atom_getwt 211L+ATOMNUMBERBASE
#define atom_putt 212L+ATOMNUMBERBASE
#define atom_puttq 213L+ATOMNUMBERBASE
#define atom_putwt 214L+ATOMNUMBERBASE
#define atom_putwtq 215L+ATOMNUMBERBASE
#define atom_addop 216L+ATOMNUMBERBASE
#define atom_rmop 217L+ATOMNUMBERBASE
#define atom_on__error 218L+ATOMNUMBERBASE
#define atom_connect 219L+ATOMNUMBERBASE
#define atom_bind 220L+ATOMNUMBERBASE
#define atom_accept 221L+ATOMNUMBERBASE
#define atom_connect2 222L+ATOMNUMBERBASE
#define atom_accept2 223L+ATOMNUMBERBASE
#define atom_sym 224L+ATOMNUMBERBASE
#define atom_unparser 225L+ATOMNUMBERBASE
#define atom_unparse 226L+ATOMNUMBERBASE
#define atom_unwparse 227L+ATOMNUMBERBASE
#define atom_qtd 228L+ATOMNUMBERBASE
#define atom_alf 229L+ATOMNUMBERBASE
#define atom_do 230L+ATOMNUMBERBASE
#define atom_empty 231L+ATOMNUMBERBASE
#define atom_put 232L+ATOMNUMBERBASE
#define atom_get 233L+ATOMNUMBERBASE
#define atom_get__if__any 234L+ATOMNUMBERBASE
#define atom_get__all 235L+ATOMNUMBERBASE
#define atom_carbon__copy 236L+ATOMNUMBERBASE
#define atom_get__max__if__any 237L+ATOMNUMBERBASE
#define atom_get__min__if__any 238L+ATOMNUMBERBASE
#define atom_get__if__any__and__put 239L+ATOMNUMBERBASE
#define atom_get__and__put__if__any 240L+ATOMNUMBERBASE
#define atom_get__and__put 241L+ATOMNUMBERBASE
#define atom_comparator 242L+ATOMNUMBERBASE
#define atom_sort 243L+ATOMNUMBERBASE
#define atom_pool 244L+ATOMNUMBERBASE
#define atom_n 245L+ATOMNUMBERBASE
#define atom_time 246L+ATOMNUMBERBASE
#define atom_signal__stream 247L+ATOMNUMBERBASE
#define atom_pipe 248L+ATOMNUMBERBASE
#define atom_system 249L+ATOMNUMBERBASE
#define atom_cd 250L+ATOMNUMBERBASE
#define atom_unlink 251L+ATOMNUMBERBASE
#define atom_mktemp 252L+ATOMNUMBERBASE
#define atom_access 253L+ATOMNUMBERBASE
#define atom_chmod 254L+ATOMNUMBERBASE
#define atom_umask 255L+ATOMNUMBERBASE
#define atom_getenv 256L+ATOMNUMBERBASE
#define atom_putenv 257L+ATOMNUMBERBASE
#define atom_kill 258L+ATOMNUMBERBASE
#define atom_fork 259L+ATOMNUMBERBASE
#define atom_fork__with__pipes 260L+ATOMNUMBERBASE
#define atom_inet 261L+ATOMNUMBERBASE
#define atom_fread 262L+ATOMNUMBERBASE
#define atom_feof 263L+ATOMNUMBERBASE
#define atom_sync 264L+ATOMNUMBERBASE
#define atom_parent 265L+ATOMNUMBERBASE
#define atom_child 266L+ATOMNUMBERBASE
#define atom_fseek 267L+ATOMNUMBERBASE
#define atom_ftell 268L+ATOMNUMBERBASE
#define atom_fclose 269L+ATOMNUMBERBASE
#define atom_stdio 270L+ATOMNUMBERBASE
#define atom_flush 271L+ATOMNUMBERBASE
#define atom_puts 272L+ATOMNUMBERBASE
#define atom_bind__mcast 273L+ATOMNUMBERBASE
#define atom_send__mcast 274L+ATOMNUMBERBASE
#define atom_builtin 275L+ATOMNUMBERBASE
#define atom_integer__arithmetics 276L+ATOMNUMBERBASE
#define atom_floating__arithmetics 277L+ATOMNUMBERBASE
#define atom_bblt__add 278L+ATOMNUMBERBASE
#define atom_bblt__sub 279L+ATOMNUMBERBASE
#define atom_bblt__mult 280L+ATOMNUMBERBASE
#define atom_bblt__div 281L+ATOMNUMBERBASE
#define atom_modulo 282L+ATOMNUMBERBASE
#define atom_bblt__mod 283L+ATOMNUMBERBASE
#define atom_and 284L+ATOMNUMBERBASE
#define atom_bblt__and 285L+ATOMNUMBERBASE
#define atom_or 286L+ATOMNUMBERBASE
#define atom_bblt__or 287L+ATOMNUMBERBASE
#define atom_exclusive__or 288L+ATOMNUMBERBASE
#define atom_bblt__exclusive__or 289L+ATOMNUMBERBASE
#define atom_shift__left 290L+ATOMNUMBERBASE
#define atom_bblt__lshift 291L+ATOMNUMBERBASE
#define atom_shift__right 292L+ATOMNUMBERBASE
#define atom_bblt__rshift 293L+ATOMNUMBERBASE
#define atom_complement 294L+ATOMNUMBERBASE
#define atom_bblt__complement 295L+ATOMNUMBERBASE
#define atom_bblt__plus 296L+ATOMNUMBERBASE
#define atom_bblt__minus 297L+ATOMNUMBERBASE
#define atom_floating__point__add 298L+ATOMNUMBERBASE
#define atom_bblt__float__add 299L+ATOMNUMBERBASE
#define atom_floating__point__subtract 300L+ATOMNUMBERBASE
#define atom_bblt__float__sub 301L+ATOMNUMBERBASE
#define atom_floating__point__multiply 302L+ATOMNUMBERBASE
#define atom_bblt__float__mult 303L+ATOMNUMBERBASE
#define atom_floating__point__divide 304L+ATOMNUMBERBASE
#define atom_bblt__float__div 305L+ATOMNUMBERBASE
#define atom_floating__point__power 306L+ATOMNUMBERBASE
#define atom_bblt__float__pow 307L+ATOMNUMBERBASE
#define atom_floating__point__sin 308L+ATOMNUMBERBASE
#define atom_bblt__float__sin 309L+ATOMNUMBERBASE
#define atom_floating__point__cos 310L+ATOMNUMBERBASE
#define atom_bblt__float__cos 311L+ATOMNUMBERBASE
#define atom_floating__point__tan 312L+ATOMNUMBERBASE
#define atom_bblt__float__tan 313L+ATOMNUMBERBASE
#define atom_floating__point__asin 314L+ATOMNUMBERBASE
#define atom_bblt__float__asin 315L+ATOMNUMBERBASE
#define atom_floating__point__acos 316L+ATOMNUMBERBASE
#define atom_bblt__float__acos 317L+ATOMNUMBERBASE
#define atom_floating__point__atan 318L+ATOMNUMBERBASE
#define atom_bblt__float__atan 319L+ATOMNUMBERBASE
#define atom_floating__point__sinh 320L+ATOMNUMBERBASE
#define atom_bblt__float__sinh 321L+ATOMNUMBERBASE
#define atom_floating__point__cosh 322L+ATOMNUMBERBASE
#define atom_bblt__float__cosh 323L+ATOMNUMBERBASE
#define atom_floating__point__tanh 324L+ATOMNUMBERBASE
#define atom_bblt__float__tanh 325L+ATOMNUMBERBASE
#define atom_floating__point__exp 326L+ATOMNUMBERBASE
#define atom_bblt__float__exp 327L+ATOMNUMBERBASE
#define atom_floating__point__log 328L+ATOMNUMBERBASE
#define atom_bblt__float__log 329L+ATOMNUMBERBASE
#define atom_floating__point__sqrt 330L+ATOMNUMBERBASE
#define atom_bblt__float__sqrt 331L+ATOMNUMBERBASE
#define atom_floating__point__ceil 332L+ATOMNUMBERBASE
#define atom_bblt__float__ceil 333L+ATOMNUMBERBASE
#define atom_floating__point__floor 334L+ATOMNUMBERBASE
#define atom_bblt__float__floor 335L+ATOMNUMBERBASE
#define atom_floating__point__to__integer 336L+ATOMNUMBERBASE
#define atom_bblt__fix 337L+ATOMNUMBERBASE
#define atom_current__node 338L+ATOMNUMBERBASE
#define atom_bblt__current__node 339L+ATOMNUMBERBASE
#define atom_object 340L+ATOMNUMBERBASE
#define atom_gblt__hash 341L+ATOMNUMBERBASE
#define atom_gblt__deep__hash 342L+ATOMNUMBERBASE
#define atom_gblt__compare 343L+ATOMNUMBERBASE
#define atom_gblt__current__prio 344L+ATOMNUMBERBASE
#define atom_gblt__wait 345L+ATOMNUMBERBASE
#define atom_gblt__list 346L+ATOMNUMBERBASE
#define atom_gblt__atom 347L+ATOMNUMBERBASE
#define atom_gblt__integer 348L+ATOMNUMBERBASE
#define atom_atomic 349L+ATOMNUMBERBASE
#define atom_gblt__atomic 350L+ATOMNUMBERBASE
#define atom_gblt__float 351L+ATOMNUMBERBASE
#define atom_gblt__size__of__vector 352L+ATOMNUMBERBASE
#define atom_gblt__element__of__vector 353L+ATOMNUMBERBASE
#define atom_gblt__size__of__string 354L+ATOMNUMBERBASE
#define atom_gblt__element__size__of__string 355L+ATOMNUMBERBASE
#define atom_gblt__is__string 356L+ATOMNUMBERBASE
#define atom_gblt__element__of__string 357L+ATOMNUMBERBASE
#define atom_gblt__pfunctor 358L+ATOMNUMBERBASE
#define atom_gblt__arity 359L+ATOMNUMBERBASE
#define atom_any 360L+ATOMNUMBERBASE
#define atom_gblt__arg 361L+ATOMNUMBERBASE
#define atom_gblt__less 362L+ATOMNUMBERBASE
#define atom_gblt__greater__or__eq 363L+ATOMNUMBERBASE
#define atom_gblt__greater 364L+ATOMNUMBERBASE
#define atom_gblt__less__or__eq 365L+ATOMNUMBERBASE
#define atom_gblt__eq 366L+ATOMNUMBERBASE
#define atom_gblt__not__eq 367L+ATOMNUMBERBASE
#define atom_gblt__diff 368L+ATOMNUMBERBASE
#define atom_gblt__and 369L+ATOMNUMBERBASE
#define atom_gblt__or 370L+ATOMNUMBERBASE
#define atom_gblt__exclusive__or 371L+ATOMNUMBERBASE
#define atom_gblt__rshift 372L+ATOMNUMBERBASE
#define atom_gblt__lshift 373L+ATOMNUMBERBASE
#define atom_gblt__add 374L+ATOMNUMBERBASE
#define atom_gblt__subtract 375L+ATOMNUMBERBASE
#define atom_gblt__multiply 376L+ATOMNUMBERBASE
#define atom_gblt__divide 377L+ATOMNUMBERBASE
#define atom_gblt__modulo 378L+ATOMNUMBERBASE
#define atom_gblt__complement 379L+ATOMNUMBERBASE
#define atom_gblt__plus 380L+ATOMNUMBERBASE
#define atom_gblt__minus 381L+ATOMNUMBERBASE
#define atom_gblt__fix 382L+ATOMNUMBERBASE
#define atom_gblt__tag 383L+ATOMNUMBERBASE
#define atom_gblt__value 384L+ATOMNUMBERBASE
#define atom_bound 385L+ATOMNUMBERBASE
#define atom_gblt__display__console 386L+ATOMNUMBERBASE
#define atom_hash 387L+ATOMNUMBERBASE
#define atom_compare 388L+ATOMNUMBERBASE
#define atom_current__priority 389L+ATOMNUMBERBASE
#define atom_wait 390L+ATOMNUMBERBASE
#define atom_vector__element 391L+ATOMNUMBERBASE
#define atom_string__element 392L+ATOMNUMBERBASE
#define atom_diff 393L+ATOMNUMBERBASE
#define atom_tag__and__value 394L+ATOMNUMBERBASE
#define atom_display__console 395L+ATOMNUMBERBASE
#define atom_put__console 396L+ATOMNUMBERBASE
#define atom__24 397L+ATOMNUMBERBASE
#define atom_interrupt 398L+ATOMNUMBERBASE
#define atom_e 399L+ATOMNUMBERBASE
#define atom_otherwise 400L+ATOMNUMBERBASE
#define atom_alternatively 401L+ATOMNUMBERBASE
#define atom_head 402L+ATOMNUMBERBASE
#define atom_cdr 403L+ATOMNUMBERBASE
#define atom_car 404L+ATOMNUMBERBASE
#define atom_inline 405L+ATOMNUMBERBASE
#define atom_new 406L+ATOMNUMBERBASE
#define atom_generic 407L+ATOMNUMBERBASE
#define atom_lower__priority 408L+ATOMNUMBERBASE
#define atom_lab 409L+ATOMNUMBERBASE
#define atom_a 410L+ATOMNUMBERBASE
#define atom_clause 411L+ATOMNUMBERBASE
#define atom_il 412L+ATOMNUMBERBASE
#define atom_gg 413L+ATOMNUMBERBASE
#define atom_gp 414L+ATOMNUMBERBASE
#define atom_gb 415L+ATOMNUMBERBASE
#define atom__24macroexpanded 416L+ATOMNUMBERBASE
#define atom_gcall 417L+ATOMNUMBERBASE
#define atom_xcall 418L+ATOMNUMBERBASE
#define atom_priority 419L+ATOMNUMBERBASE
#define atom_node 420L+ATOMNUMBERBASE
#define atom_xpcall 421L+ATOMNUMBERBASE
#define atom_pcall 422L+ATOMNUMBERBASE
#define atom_xlcall 423L+ATOMNUMBERBASE
#define atom_lcall 424L+ATOMNUMBERBASE
#define atom_xthrow 425L+ATOMNUMBERBASE
#define atom_throw 426L+ATOMNUMBERBASE
#define atom_rename 427L+ATOMNUMBERBASE
#define atom_mkfunct 428L+ATOMNUMBERBASE
#define atom_mkvect 429L+ATOMNUMBERBASE
#define atom_cons 430L+ATOMNUMBERBASE
#define atom_version_203_2E005 431L+ATOMNUMBERBASE
#define atom_Thu_20Feb_20_2013_2017_3A11_3A01_20JST_202003 432L+ATOMNUMBERBASE
#define atom_end__sw 433L+ATOMNUMBERBASE
#define atom_funct 434L+ATOMNUMBERBASE
#define atom_abs 435L+ATOMNUMBERBASE
#define atom_rel 436L+ATOMNUMBERBASE
#define atom_qp 437L+ATOMNUMBERBASE
#define atom_known 438L+ATOMNUMBERBASE
#define atom_other 439L+ATOMNUMBERBASE
#define atom_alter 440L+ATOMNUMBERBASE
#define atom_l 441L+ATOMNUMBERBASE
#define atom_x 442L+ATOMNUMBERBASE
#define atom_if__ref 443L+ATOMNUMBERBASE
#define atom_if__not__ref 444L+ATOMNUMBERBASE
#define atom_v 445L+ATOMNUMBERBASE
#define atom_deref 446L+ATOMNUMBERBASE
#define atom_sw__tag 447L+ATOMNUMBERBASE
#define atom_case__label 448L+ATOMNUMBERBASE
#define atom_if__not__int 449L+ATOMNUMBERBASE
#define atom_if__int 450L+ATOMNUMBERBASE
#define atom_f 451L+ATOMNUMBERBASE
#define atom_o 452L+ATOMNUMBERBASE
#define atom_if__not__gobj 453L+ATOMNUMBERBASE
#define atom_if__not__class 454L+ATOMNUMBERBASE
#define atom_goto 455L+ATOMNUMBERBASE
#define atom_if__not 456L+ATOMNUMBERBASE
#define atom_if__funct__not 457L+ATOMNUMBERBASE
#define atom_sw__sym 458L+ATOMNUMBERBASE
#define atom_sw__int 459L+ATOMNUMBERBASE
#define atom_sw__funct 460L+ATOMNUMBERBASE
#define atom_case__sym 461L+ATOMNUMBERBASE
#define atom_case__int 462L+ATOMNUMBERBASE
#define atom_case__funct 463L+ATOMNUMBERBASE
#define atom_label 464L+ATOMNUMBERBASE
#define atom_gblt__pred 465L+ATOMNUMBERBASE
#define atom_guard__generic 466L+ATOMNUMBERBASE
#define atom_eq 467L+ATOMNUMBERBASE
#define atom_if__not__eq 468L+ATOMNUMBERBASE
#define atom_load__generic__arg 469L+ATOMNUMBERBASE
#define atom_make__cons 470L+ATOMNUMBERBASE
#define atom_make__functor 471L+ATOMNUMBERBASE
#define atom_alloc__functor__id 472L+ATOMNUMBERBASE
#define atom_make__vector 473L+ATOMNUMBERBASE
#define atom_const 474L+ATOMNUMBERBASE
#define atom_alloc__value 475L+ATOMNUMBERBASE
#define atom_alloc__const 476L+ATOMNUMBERBASE
#define atom_exec 477L+ATOMNUMBERBASE
#define atom_execute 478L+ATOMNUMBERBASE
#define atom_proceed 479L+ATOMNUMBERBASE
#define atom_bblt 480L+ATOMNUMBERBASE
#define atom_push__goal 481L+ATOMNUMBERBASE
#define atom_gnew 482L+ATOMNUMBERBASE
#define atom_new__generic 483L+ATOMNUMBERBASE
#define atom_call__generic 484L+ATOMNUMBERBASE
#define atom_throw__goal 485L+ATOMNUMBERBASE
#define atom_set__pred 486L+ATOMNUMBERBASE
#define atom_ext 487L+ATOMNUMBERBASE
#define atom_heappos 488L+ATOMNUMBERBASE
#define atom_set__ext__pred 489L+ATOMNUMBERBASE
#define atom_enq__at__prio__no__check 490L+ATOMNUMBERBASE
#define atom_enq__at__prio 491L+ATOMNUMBERBASE
#define atom_enq__at__lower__prio__no__check 492L+ATOMNUMBERBASE
#define atom_enq__at__lower__prio 493L+ATOMNUMBERBASE
#define atom_alloc__var 494L+ATOMNUMBERBASE
#define atom_make__space 495L+ATOMNUMBERBASE
#define atom_unify__value 496L+ATOMNUMBERBASE
#define atom_unify 497L+ATOMNUMBERBASE
#define atom_set__const 498L+ATOMNUMBERBASE
#define atom_set__value 499L+ATOMNUMBERBASE
#define atom_set__newvar 500L+ATOMNUMBERBASE
#define atom_store__generic__arg 501L+ATOMNUMBERBASE
#define atom_load__const 502L+ATOMNUMBERBASE
#define atom_get__elem 503L+ATOMNUMBERBASE
#define atom_load__newvar 504L+ATOMNUMBERBASE
#define atom_move 505L+ATOMNUMBERBASE
#define atom_r 506L+ATOMNUMBERBASE
#define atom_guse 507L+ATOMNUMBERBASE
#define atom_set__qp 508L+ATOMNUMBERBASE
#define atom_case__default 509L+ATOMNUMBERBASE
#define atom_clear__reason 510L+ATOMNUMBERBASE
#define atom_user__error 511L+ATOMNUMBERBASE
#define atom_alloc__elem 512L+ATOMNUMBERBASE
#define atom_if__list 513L+ATOMNUMBERBASE
#define atom_if__not__list 514L+ATOMNUMBERBASE
#define atom_if__funct 515L+ATOMNUMBERBASE
#define atom_if__not__funct 516L+ATOMNUMBERBASE
#define atom_set__elem 517L+ATOMNUMBERBASE
#define atom_gblt 518L+ATOMNUMBERBASE
#define atom_equiv 519L+ATOMNUMBERBASE
#define atom_info 520L+ATOMNUMBERBASE
#define atom_class 521L+ATOMNUMBERBASE
#define atom_pred 522L+ATOMNUMBERBASE
#define atom_true 523L+ATOMNUMBERBASE
#define atom_functor__table 524L+ATOMNUMBERBASE
#define atom_merge 525L+ATOMNUMBERBASE
#define atom_builtin__utility 526L+ATOMNUMBERBASE
#define atom_g 527L+ATOMNUMBERBASE
#define atom__60 528L+ATOMNUMBERBASE
#define atom__60_60 529L+ATOMNUMBERBASE
#define atom_c 530L+ATOMNUMBERBASE
#define atom_key 531L+ATOMNUMBERBASE
#define atom_lf 532L+ATOMNUMBERBASE
#define atom_cr 533L+ATOMNUMBERBASE
#define atom_b 534L+ATOMNUMBERBASE
#define atom_fix 535L+ATOMNUMBERBASE
#define atom_expanded 536L+ATOMNUMBERBASE
#define atom_unbound 537L+ATOMNUMBERBASE
#define atom_new__functor 538L+ATOMNUMBERBASE
#define atom_set__string__element 539L+ATOMNUMBERBASE
#define atom_set__vector__element 540L+ATOMNUMBERBASE
#define atom_new__string 541L+ATOMNUMBERBASE
#define atom_new__vector 542L+ATOMNUMBERBASE
#define atom_predicate__to__code 543L+ATOMNUMBERBASE
#define atom_string__less__than 544L+ATOMNUMBERBASE
#define atom_string__not__less__than 545L+ATOMNUMBERBASE
#define atom_code 546L+ATOMNUMBERBASE
#define atom_general 547L+ATOMNUMBERBASE
#define atom__5C 548L+ATOMNUMBERBASE
#define atom_byte__string 549L+ATOMNUMBERBASE
#define atom_inputfile 550L+ATOMNUMBERBASE
#define atom_fileopen 551L+ATOMNUMBERBASE
#define atom_fileoutput 552L+ATOMNUMBERBASE
#define atom_compiling__module 553L+ATOMNUMBERBASE
#define atom_compiling__predicate 554L+ATOMNUMBERBASE
#define atom_ambiguous 555L+ATOMNUMBERBASE
#define atom_token 556L+ATOMNUMBERBASE
#define atom_was 557L+ATOMNUMBERBASE
#define atom_found 558L+ATOMNUMBERBASE
#define atom_end 559L+ATOMNUMBERBASE
#define atom__24VAR 560L+ATOMNUMBERBASE
#define atom_with 561L+ATOMNUMBERBASE
