#include <klic/functorstuffs.h>

#define functor_element_2	0L+FUNCTORNUMBERBASE
#define functor_size_1	1L+FUNCTORNUMBERBASE
#define functor_set__element_3	2L+FUNCTORNUMBERBASE
#define functor_set__element_4	3L+FUNCTORNUMBERBASE
#define functor_split_3	4L+FUNCTORNUMBERBASE
#define functor_join_2	5L+FUNCTORNUMBERBASE
#define functor_vector_1	6L+FUNCTORNUMBERBASE
#define functor_string_2	7L+FUNCTORNUMBERBASE
#define functor_element__size_1	8L+FUNCTORNUMBERBASE
#define functor_search__character_4	9L+FUNCTORNUMBERBASE
#define functor_less__than_1	10L+FUNCTORNUMBERBASE
#define functor_not__less__than_1	11L+FUNCTORNUMBERBASE
#define functor_estring_3	12L+FUNCTORNUMBERBASE
#define functor_print_1	13L+FUNCTORNUMBERBASE
#define functor_int_1	14L+FUNCTORNUMBERBASE
#define functor_sin_1	15L+FUNCTORNUMBERBASE
#define functor_cos_1	16L+FUNCTORNUMBERBASE
#define functor_tan_1	17L+FUNCTORNUMBERBASE
#define functor_asin_1	18L+FUNCTORNUMBERBASE
#define functor_acos_1	19L+FUNCTORNUMBERBASE
#define functor_atan_1	20L+FUNCTORNUMBERBASE
#define functor_sinh_1	21L+FUNCTORNUMBERBASE
#define functor_cosh_1	22L+FUNCTORNUMBERBASE
#define functor_tanh_1	23L+FUNCTORNUMBERBASE
#define functor_asinh_1	24L+FUNCTORNUMBERBASE
#define functor_acosh_1	25L+FUNCTORNUMBERBASE
#define functor_atanh_1	26L+FUNCTORNUMBERBASE
#define functor_exp_1	27L+FUNCTORNUMBERBASE
#define functor_log_1	28L+FUNCTORNUMBERBASE
#define functor_sqrt_1	29L+FUNCTORNUMBERBASE
#define functor_ceil_1	30L+FUNCTORNUMBERBASE
#define functor_floor_1	31L+FUNCTORNUMBERBASE
#define functor_round_1	32L+FUNCTORNUMBERBASE
#define functor_plus_1	33L+FUNCTORNUMBERBASE
#define functor_minus_1	34L+FUNCTORNUMBERBASE
#define functor_add_2	35L+FUNCTORNUMBERBASE
#define functor_subtract_2	36L+FUNCTORNUMBERBASE
#define functor_multiply_2	37L+FUNCTORNUMBERBASE
#define functor_divide_2	38L+FUNCTORNUMBERBASE
#define functor_pow_2	39L+FUNCTORNUMBERBASE
#define functor_not__greater__than_1	40L+FUNCTORNUMBERBASE
#define functor_greater__than_1	41L+FUNCTORNUMBERBASE
#define functor_equal_1	42L+FUNCTORNUMBERBASE
#define functor_not__equal_1	43L+FUNCTORNUMBERBASE
#define functor_float_0	44L+FUNCTORNUMBERBASE
#define functor_module_1	45L+FUNCTORNUMBERBASE
#define functor_name_1	46L+FUNCTORNUMBERBASE
#define functor_arity_1	47L+FUNCTORNUMBERBASE
#define functor_apply_1	48L+FUNCTORNUMBERBASE
#define functor_predicate_0	49L+FUNCTORNUMBERBASE
#define functor_module_0	50L+FUNCTORNUMBERBASE
#define functor_defined_2	51L+FUNCTORNUMBERBASE
#define functor_reduce_0	52L+FUNCTORNUMBERBASE
#define functor_step_4	53L+FUNCTORNUMBERBASE
#define functor_arg_2	54L+FUNCTORNUMBERBASE
#define functor_setarg_4	55L+FUNCTORNUMBERBASE
#define functor_predicate_4	56L+FUNCTORNUMBERBASE
#define functor_id_1	57L+FUNCTORNUMBERBASE
#define functor_set__predicate_2	58L+FUNCTORNUMBERBASE
#define functor_normal_1	59L+FUNCTORNUMBERBASE
#define functor_get__atom_2	60L+FUNCTORNUMBERBASE
#define functor_get__atom__name_2	61L+FUNCTORNUMBERBASE
#define functor_intern_2	62L+FUNCTORNUMBERBASE
#define functor_power_2	63L+FUNCTORNUMBERBASE
#define functor_string_1	64L+FUNCTORNUMBERBASE
#define functor_normal_2	65L+FUNCTORNUMBERBASE
#define functor__7C_2	66L+FUNCTORNUMBERBASE
#define functor__2C_2	67L+FUNCTORNUMBERBASE
#define functor_abnormal_2	68L+FUNCTORNUMBERBASE
#define functor_variable_1	69L+FUNCTORNUMBERBASE
#define functor_variable_4	70L+FUNCTORNUMBERBASE
#define functor_error_1	71L+FUNCTORNUMBERBASE
#define functor_number_1	72L+FUNCTORNUMBERBASE
#define functor_integer_1	73L+FUNCTORNUMBERBASE
#define functor_floating__point_1	74L+FUNCTORNUMBERBASE
#define functor_prefix_2	75L+FUNCTORNUMBERBASE
#define functor_infix_2	76L+FUNCTORNUMBERBASE
#define functor_ops_3	77L+FUNCTORNUMBERBASE
#define functor_postfix_1	78L+FUNCTORNUMBERBASE
#define functor_op_3	79L+FUNCTORNUMBERBASE
#define functor_atom_1	80L+FUNCTORNUMBERBASE
#define functor_list_1	81L+FUNCTORNUMBERBASE
#define functor_functor_1	82L+FUNCTORNUMBERBASE
#define functor_getc_1	83L+FUNCTORNUMBERBASE
#define functor_vtab_2	84L+FUNCTORNUMBERBASE
#define functor__3D_2	85L+FUNCTORNUMBERBASE
#define functor_var_4	86L+FUNCTORNUMBERBASE
#define functor_octal_1	87L+FUNCTORNUMBERBASE
#define functor_ungetc_1	88L+FUNCTORNUMBERBASE
#define functor_stderr_1	89L+FUNCTORNUMBERBASE
#define functor_linecount_1	90L+FUNCTORNUMBERBASE
#define functor_putc_1	91L+FUNCTORNUMBERBASE
#define functor_fwrite_1	92L+FUNCTORNUMBERBASE
#define functor_fflush_1	93L+FUNCTORNUMBERBASE
#define functor_s_2	94L+FUNCTORNUMBERBASE
#define functor_open_1	95L+FUNCTORNUMBERBASE
#define functor_var_2	96L+FUNCTORNUMBERBASE
#define functor_unknown_1	97L+FUNCTORNUMBERBASE
#define functor_fwrite_2	98L+FUNCTORNUMBERBASE
#define functor_stdin_1	99L+FUNCTORNUMBERBASE
#define functor_stdout_1	100L+FUNCTORNUMBERBASE
#define functor_read__open_2	101L+FUNCTORNUMBERBASE
#define functor_write__open_2	102L+FUNCTORNUMBERBASE
#define functor_append__open_2	103L+FUNCTORNUMBERBASE
#define functor_update__open_2	104L+FUNCTORNUMBERBASE
#define functor_unix_1	105L+FUNCTORNUMBERBASE
#define functor_string__output_2	106L+FUNCTORNUMBERBASE
#define functor_string__input_2	107L+FUNCTORNUMBERBASE
#define functor_gett_1	108L+FUNCTORNUMBERBASE
#define functor_getwt_1	109L+FUNCTORNUMBERBASE
#define functor_putt_1	110L+FUNCTORNUMBERBASE
#define functor_puttq_1	111L+FUNCTORNUMBERBASE
#define functor_putwt_1	112L+FUNCTORNUMBERBASE
#define functor_putwtq_1	113L+FUNCTORNUMBERBASE
#define functor_addop_3	114L+FUNCTORNUMBERBASE
#define functor_rmop_2	115L+FUNCTORNUMBERBASE
#define functor_on__error_1	116L+FUNCTORNUMBERBASE
#define functor_connect_2	117L+FUNCTORNUMBERBASE
#define functor_bind_2	118L+FUNCTORNUMBERBASE
#define functor_accept_1	119L+FUNCTORNUMBERBASE
#define functor_connect2_2	120L+FUNCTORNUMBERBASE
#define functor_accept2_1	121L+FUNCTORNUMBERBASE
#define functor_call_6	122L+FUNCTORNUMBERBASE
#define functor_fx_1	123L+FUNCTORNUMBERBASE
#define functor_fy_1	124L+FUNCTORNUMBERBASE
#define functor_xfx_1	125L+FUNCTORNUMBERBASE
#define functor_xfy_1	126L+FUNCTORNUMBERBASE
#define functor_yfx_1	127L+FUNCTORNUMBERBASE
#define functor_xf_1	128L+FUNCTORNUMBERBASE
#define functor_yf_1	129L+FUNCTORNUMBERBASE
#define functor_none_1	130L+FUNCTORNUMBERBASE
#define functor_do_1	131L+FUNCTORNUMBERBASE
#define functor_empty_1	132L+FUNCTORNUMBERBASE
#define functor_put_1	133L+FUNCTORNUMBERBASE
#define functor_get_1	134L+FUNCTORNUMBERBASE
#define functor_get__if__any_1	135L+FUNCTORNUMBERBASE
#define functor_get__all_1	136L+FUNCTORNUMBERBASE
#define functor_carbon__copy_1	137L+FUNCTORNUMBERBASE
#define functor_get__max__if__any_1	138L+FUNCTORNUMBERBASE
#define functor_get__min__if__any_1	139L+FUNCTORNUMBERBASE
#define functor_empty_2	140L+FUNCTORNUMBERBASE
#define functor_put_2	141L+FUNCTORNUMBERBASE
#define functor_get_2	142L+FUNCTORNUMBERBASE
#define functor_get__if__any_2	143L+FUNCTORNUMBERBASE
#define functor_get__all_2	144L+FUNCTORNUMBERBASE
#define functor_carbon__copy_2	145L+FUNCTORNUMBERBASE
#define functor_get__if__any__and__put_3	146L+FUNCTORNUMBERBASE
#define functor_get__and__put__if__any_4	147L+FUNCTORNUMBERBASE
#define functor_get__and__put_3	148L+FUNCTORNUMBERBASE
#define functor_put_3	149L+FUNCTORNUMBERBASE
#define functor_call_5	150L+FUNCTORNUMBERBASE
#define functor_pool_2	151L+FUNCTORNUMBERBASE
#define functor_n_4	152L+FUNCTORNUMBERBASE
#define functor_time_2	153L+FUNCTORNUMBERBASE
#define functor_time_3	154L+FUNCTORNUMBERBASE
#define functor_signal__stream_2	155L+FUNCTORNUMBERBASE
#define functor_pipe_1	156L+FUNCTORNUMBERBASE
#define functor_system_2	157L+FUNCTORNUMBERBASE
#define functor_cd_2	158L+FUNCTORNUMBERBASE
#define functor_unlink_2	159L+FUNCTORNUMBERBASE
#define functor_mktemp_2	160L+FUNCTORNUMBERBASE
#define functor_access_3	161L+FUNCTORNUMBERBASE
#define functor_chmod_3	162L+FUNCTORNUMBERBASE
#define functor_umask_1	163L+FUNCTORNUMBERBASE
#define functor_umask_2	164L+FUNCTORNUMBERBASE
#define functor_getenv_2	165L+FUNCTORNUMBERBASE
#define functor_putenv_2	166L+FUNCTORNUMBERBASE
#define functor_kill_3	167L+FUNCTORNUMBERBASE
#define functor_fork_1	168L+FUNCTORNUMBERBASE
#define functor_fork__with__pipes_1	169L+FUNCTORNUMBERBASE
#define functor_inet_1	170L+FUNCTORNUMBERBASE
#define functor_inet_2	171L+FUNCTORNUMBERBASE
#define functor_fread_2	172L+FUNCTORNUMBERBASE
#define functor_feof_1	173L+FUNCTORNUMBERBASE
#define functor_sync_1	174L+FUNCTORNUMBERBASE
#define functor_parent_3	175L+FUNCTORNUMBERBASE
#define functor_child_2	176L+FUNCTORNUMBERBASE
#define functor_fseek_3	177L+FUNCTORNUMBERBASE
#define functor_ftell_1	178L+FUNCTORNUMBERBASE
#define functor_fclose_1	179L+FUNCTORNUMBERBASE
#define functor_stdio_1	180L+FUNCTORNUMBERBASE
#define functor_puts_1	181L+FUNCTORNUMBERBASE
#define functor_bind__mcast_2	182L+FUNCTORNUMBERBASE
#define functor_send__mcast_2	183L+FUNCTORNUMBERBASE
